location = __PATH__/config.js {
  alias __INSTALL_DIR__/config.js;
  more_set_headers "Cache-Control: no-cache, no-store, must-revalidate";
}

location __PATH__/ {
  alias __INSTALL_DIR__/;
  index index.html;
  try_files $uri $uri/ __PATH__/index.html;
}
